// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eufcwtskludeuandddws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1ZmN3dHNrbHVkZXVhbmRkZHdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NjU2MjMsImV4cCI6MjA2NTU0MTYyM30.FXhZPRQHBVLdz02hCAgI5sHuzR55ZohO6QGM5G6DEfQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);